# Panda Series 
A series is one dimensional labeled array capable of holding any data type. The axis labeled are collectively called the index

## creating Series

.\venv\Scripts\Activate.ps1
pip install pandas 
pip install numpy

In [2]:
import numpy as np
import pandas as pd

In [2]:
label=['a','b','c']
list=[10,20,30]
arr=np.array([4,5,6])
d={1:10,2:20,6:30}

In [ ]:
pd.Series(list,index=arr)

4    10
5    20
6    30
dtype: int64

In [4]:
pd.Series(d)

1    10
2    20
6    30
dtype: int64

### Data Frames 
combination of multiple series

### creating of data frame 

u can create a data frame using dictionary and list

In [ ]:
## dictionary 
data ={
    'Name':['Aman','Panda','Kalu','Mahi','Priya'],
    'Age':[20,21,22,23,24],
    'City':['New York','Paris','Nigga','Swarg','bhaad'],
    'salary':[100000,20000,30000,40000,50000]
}
df = pd.DataFrame(data)
print(df)

    Name  Age      City  salary
0   Aman   20  New York  100000
1  Panda   21     Paris   20000
2   Kalu   22     Nigga   30000
3   Mahi   23     Swarg   40000
4  Priya   24     bhaad   50000

In [33]:
# pd.Series(df['City'].values,index=df['Age'].values)
df.set_index('Age')['City']

Age
20    New York
21       Paris
22       Nigga
23       Swarg
24       bhaad
Name: City, dtype: str

In [76]:
data_list=[
     ['Aman' ,20 ,'New York' , 100000],
    ['Panda' ,21 ,'Paris'  ,20000],
    [ 'Kalu'  ,22  ,'Nigga', 30000],
    ['Mahi'  ,23  ,'Swarg' ,4000],
   [ 'Priya' ,24  ,'bhaad' ,50000]
]

# pd.DataFrame(data_list)
d_list=pd.DataFrame(data_list)
d_list
# print(d_list)

       0   1         2       3
0   Aman  20  New York  100000
1  Panda  21     Paris   20000
2   Kalu  22     Nigga   30000
3   Mahi  23     Swarg    4000
4  Priya  24     bhaad   50000

In [77]:
# to set column name 
colm=["Name","Age","City","Salary"]
d_l=pd.DataFrame(data_list,columns=colm)
d_l

    Name  Age      City  Salary
0   Aman   20  New York  100000
1  Panda   21     Paris   20000
2   Kalu   22     Nigga   30000
3   Mahi   23     Swarg    4000
4  Priya   24     bhaad   50000

### Selection And indexing of column

In [74]:
d_l["City"]

0    12
1    21
2    32
3    23
4    34
Name: City, dtype: int64

In [64]:
d_l[['Name','Age']]

    Name  Age
0   Aman   20
1  Panda   21
2   Kalu   22
3   Mahi   23
4  Priya   24

### Creating New Column

In [115]:
d_l['Code']=[12,21,32,23,34]
d_l

    Name  Age      City  Salary  Code
0   Aman   20  New York  100000    12
1  Panda   21     Paris   20000    21
2   Kalu   22     Nigga   30000    32
3   Mahi   23     Swarg    4000    23
4  Priya   24     bhaad   50000    34

### Removing of Column

In [ ]:
d_l.drop('Code',axis=1,inplace=True) #inplace is used to delet from main data

In [122]:
d_l.drop(4,axis=0)

    Name  Age      City  Salary
0   Aman   20  New York  100000
1  Panda   21     Paris   20000
2   Kalu   22     Nigga   30000
3   Mahi   23     Swarg    4000

# Selecting Rows

In [128]:
d_l
d_l.loc[[0,1]]

    Name  Age      City  Salary
0   Aman   20  New York  100000
1  Panda   21     Paris   20000

In [130]:
d_l.iloc[1] # selecting from index

Name      Panda
Age          21
City      Paris
Salary    20000
Name: 1, dtype: object

### Selecting Subsets of  Rows And columns

In [133]:
d_l.loc[[1,2]][['City','Salary']]
# [[rows]][[columns]]

    City  Salary
1  Paris   20000
2  Nigga   30000

### Conditional Selection

In [138]:
d_l[d_l['Age']>22] ## which age is greater than 22

    Name  Age   City  Salary
3   Mahi   23  Swarg    4000
4  Priya   24  bhaad   50000

In [150]:
# d_l[(d_l["Age"] > 22) & (d_l["City"] == "Swarg")] ## both are same 
d_l[(d_l['Age'] > 22) & (d_l['City'] == 'Swarg')]

   Name  Age   City  Salary
3  Mahi   23  Swarg    4000

# Missing Data

In [182]:
ddata={
    'A':[1,2,np.nan,4,5],
    'B':[6,7,8,9,10],
    'C':[11,12,13,np.nan,np.nan],
    'D':[14,np.nan,np.nan,np.nan,15]
}
df=pd.DataFrame(ddata)
df

     A   B     C     D
0  1.0   6  11.0  14.0
1  2.0   7  12.0   NaN
2  NaN   8  13.0   NaN
3  4.0   9   NaN   NaN
4  5.0  10   NaN  15.0

### Finding Missing Data

In [162]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [ ]:
# df.isna().count()
df.isna().sum() ## columnwise selection

A    1
B    0
C    2
D    3
dtype: int64

### Removing Missing Data

In [ ]:
df.dropna() ## row wise

     A  B     C     D
0  1.0  6  11.0  14.0

In [184]:
df.dropna(thresh=3) ## thresh stand for min value 
## minimum utni value honi chahiye

     A   B     C     D
0  1.0   6  11.0  14.0
1  2.0   7  12.0   NaN
4  5.0  10   NaN  15.0

### Filling The Missing Data 

na - column wise 
selection 


row wise -- drop

In [170]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [ ]:
df.fillna(0) ##column wise

     A   B     C     D
0  1.0   6  11.0  14.0
1  2.0   7  12.0   0.0
2  0.0   8  13.0   0.0
3  4.0   9   0.0   0.0
4  5.0  10   0.0  15.0

In [176]:
## Filling particular data in particular row 
v={'A':0,'B':70,'C':80,'D':100}
df.fillna(value=v)

     A  B     C      D
0  1.0  1   1.0    1.0
1  2.0  2   2.0  100.0
2  0.0  3   3.0  100.0
3  4.0  4  80.0  100.0
4  5.0  5  80.0    5.0

In [177]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0